version: "3"

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: usr
      POSTGRES_DB: sqlalchemy

    ports:
      - 5432:5432
    networks:
      - stack

  frontend:
    build:
      context: ./react/apps/frontend
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - stack

  backend:
    build:
      context: ./python/apps/backend
    volumes:
      - ./python/apps/backend:/app/:cached  # Mount code to allow for hot reloading
    environment:
      MONGODB_HOST: mongodb
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      AZURE_CLIENT_ID:
      AZURE_CLIENT_SECRET:
      AZURE_TENANT_ID:
      JWT_SECRET_KEY:
    ports:
      - 8000:8000
      - - 5432:5432
    networks:
      - stack


networks:
  stack: {}
