steps:
- name: gcr.io/kaniko-project/executor:v1.3.0
  #stop storing containers in usa then paying for transfer fees
  args:
  - --destination=gcr.io/${PROJECT_ID}/mal-patent-tool:${SHORT_SHA}
  - --cache=true
  - --cache-ttl=100h
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: ['run', 'deploy', 'mal', '--image', "gcr.io/${PROJECT_ID}/mal-patent-tool:${SHORT_SHA}",'--region', 'europe-west2']
#not worth paying extra for fast build
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 3600s