steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/mal-patent-tool:${SHORT_SHA}', '.' ]
- name: gcr.io/cloud-builders/docker
  id: push
  args: [ 'push', 'gcr.io/${PROJECT_ID}/mal-patent-tool:${SHORT_SHA}']
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 3600s