steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --destination=gcr.io/${PROJECT_ID}/mal-patent-tool:${SHORT_SHA}
  - --cache=true
  - --cache-ttl=100h
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 3600s