version: "3"

services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: bitnami/mongodb:latest
    networks:
      - stack

  frontend:
    build:
      context: ./react/apps/frontend
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - stack

  backend:
    build:
      context: ./python/apps/backend
    volumes:
      - ./python/apps/backend:/app/:cached  # Mount code to allow for hot reloading
    environment:
      MONGODB_HOST: mongodb
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      AZURE_CLIENT_ID:
      AZURE_CLIENT_SECRET:
      AZURE_TENANT_ID:
      JWT_SECRET_KEY:
    ports:
      - 8000:8000
    networks:
      - stack

networks:
  stack: {}
