name: python3
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - codecov
  - fastapi
  - uvicorn
  - requests
  - oauthlib
  - pyjwt
  - passlib
  - aiocache
  - msal
  - msgpack-python
  - sqlalchemy
  - psycopg2
