name: python3
channels:
  - conda-forge
  - defaults
  - anaconda
  - esri
dependencies:
  - python=3.9
  - pycocotools
  - codecov
  - psycopg2
  - pip
  - pip:
    - oauthlib
    - pyjwt
    - passlib
    - aiocache
    - msal
    - msgpack-python
    - sqlalchemy
    - tf-models-official==2.7.0
    - pandas-gbq
    - google-cloud-bigquery
    - db-dtypes
    - mlflow
    - gcsfs
    - fsspec
    - cloudpickle
    - pandas==1.3.5
    - scikit-learn==1.0.2
    - pyarrow
    - fastapi
    - uvicorn
    - requests